### ISSUE TITLE
hicFindEnrichedContacts, doubts about method

### ISSUE THREAD

**Issue by apaytuvi** [maxplanck-ie/HiCExplorer#102]
I see that `hicFindEnrichedContacts`, its option `--method` has lots of options:

`z-score,t-score,residuals,obs/exp,p-value,pearson,nbinom-p-value,nbinom-expected,nbinom-est-dist,log-norm,chi-squared,none`

- What is `residuals`?
- In case of `p-value`, how it is calculated?

Which method is better? Are some of them better under some conditions or assumptions? What is your experience?

Thank you.

**Comment by fidelram** [comment]
Thanks for spotting this. Most of the options are no longer available.

I use to have a large collection of methods to identify enriched contacts. After much testing, negative binomial p-value `nbinom-pvalue` was quite good. This is the method that we used in our Mol. Cell publication (http://www.cell.com/molecular-cell/abstract/S1097-2765(15)00670-X). However, this and other options require an R server running in the background, which is an installation headache. That's why I deactivated many options but it seems that I still need to remove them from the help message.

**Comment by apaytuvi** [comment]
@fidelram Thanks for your comments. What if I'd like to use `nbinom-pvalue`? What if I have replicates, they are taken into account at the time to get enriched contacts?

Thank you

**Comment by fidelram** [comment]
@apaytuvi if you would like to use nbinom-pvalue you will have to dig a bit in the code. It would be great if you can make this work.

The difference with computing obs/exp and z-scores is that this does not give you the statistical power to decide about enrichments. Maybe is better if you export the data and try the HICCUPS algorithm?

Replicates are not considered.

**Comment by apaytuvi** [comment]
How might I transform the HICExplorer data to the one required by HICCUPS?

**Comment by fidelram** [comment]
@apaytuvi if you convert to Lieberman format you probably can use HICCUPS. We haven't try that.
