### ISSUE TITLE
No TADs predicted

### ISSUE THREAD

**Issue by apaytuvi** [maxplanck-ie/HiCExplorer#124]
Hi,

- I am using the last version of `HiCExplorer`, installed via `pip install HiCExplorer`.
- I am using a resolution of `50K` over the mouse `mm10` genome
- I am using the following command to calculate the scores:
`hicFindTADs TAD_score --matrix fibroblasts_50K.npz --outFileName fibroblasts_tadscores.txt --minDepth 150000 --maxDepth 500000 --numberOfProcessors 8`
- I am using the following command to predict the TADs:
`hicFindTADs find_TADs --tadScoreFile fibroblasts_tadscores.txt_zscore_matrix.h5 --outPrefix fibroblasts_tads`

However, no TADs predicted in any of the different samples I have.

`INFO:hicFindTADs:Number of boundaries for delta 0.01 and pval 0.01: 0`

In order to get TADs, I have to set `--pvalue 1`. I have also plotted the values in `fibroblasts_tads_score.bedgraph`, this is the result (red lines delimit the different chromosomes):

![image](https://user-images.githubusercontent.com/11228225/30649915-d52a7a00-9e21-11e7-8191-a10f3edb3852.png)

What should I do?

TADs are there for sure, this is a part of the chromosome 1 (TADs shown -black lines- come from another algorithm):

![image2](https://user-images.githubusercontent.com/11228225/30650013-1dbef2dc-9e22-11e7-8a9c-02379f4d380c.png)

**Comment by joachimwolff** [comment]
Dear apaytuvi,

the reason is the used multi correction method in hicFindTADs. In this version we use the Bonferroni correction which is very strict, i.e. only p-values are accepted with a `p-value <= p-value / number of hypothesis`. See [Wikipedia](https://en.wikipedia.org/wiki/Bonferroni_correction). In the next release we will add FDR correction, which is in your case the better choice ([Wikipedia](https://en.wikipedia.org/wiki/False_discovery_rate)). 

If you like to use the FDR right now you can be a beta tester for the next release. All you have to do is to checkout the develop branch and install it by hand. I can give you support on this if needed.
Otherwise you have to wait until we release a new version but I hope this will be soon. 

Best,

Joachim

**Comment by joachimwolff** [comment]
With release 1.8 the FDR feature is included in upstream.
